version: '2.1'
services:
  web:
    container_name: react-flask
    build: .
    command: tail -f /dev/null
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      predicthq_token: ${predicthq_token}
      REACT_APP_GOOGLE_MAPS_KEY: ${REACT_APP_GOOGLE_MAPS_KEY}
      twitter_token: ${twitter_token}
      CODECLIMATE_REPO_TOKEN: ${CODECLIMATE_REPO_TOKEN}

    ports:
      - "3000:3000"
      - "5000:5000"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"